getoutreach/gobox

bootstrap.lock
**What this PR does / why we need it**: This PR updtes devbase from the branch to the released version 
**JIRA ID**: DT-0
=> fix(devbase): use v1.1.0

pkg/trace/honeycomb.go
[DT-466](https://outreach-io.atlassian.net/browse/DT-466)
Updates the go-outreach trace logic with a `presendHook` to add certain
service-level tags to every outgoing span.  For now, these include the
`app.Info` tags and the `dev.email` tag.  I expect more will be added in
the future.
These extra tags help to enrich the "leaf" spans of the trace, making
large "GROUP BY"-style queries more practical.  We use this all the time
in the flagship, for example summing DB time by `rails.controller`.
This gets us started towards doing the same for Go services.
Honeycomb charges us by the even (ie. span) not by the size of those
spans, so these extra tags are effectively free.
=> feat: DT-466 Make some tags appear on all spans

pkg/sshhelper/ssh_auth.go
**What this PR does / why we need it**:
If merged intent would be to pull this into bootstrap so that it can be
run without prompting for a passpharase on every run.
Will also check the agent's existing keys when adding a new key so no
prompting is needed if the agent already contains the key.
Tested this locally by replacing the version of `gobox` that bootstrap uses with this version. I then built `bootstrap` like so
```
go build  -ldflags "-X github.com/getoutreach/go-outreach/v2/pkg/app.Version=v6.13.0" -o bin/bootstrap cmd/bootstrap/bootstrap.go
```
This way when executing the binary it would try to clone a real version of itself. Was able to skip the passphrase check and clone the repo using the existing agent.
=> feat: use existing ssh agent if present

README.md
**What this PR does / why we need it**: Add a link to the logger tool from the README. Logger is awesome and I want more people to know about it!
**JIRA ID**: DT-0
=> docs: link to the logger tool from README

pkg/updater/updater.go
**What this PR does / why we need it**: Instead of using the token from file, use one from `gh` CLI if available.
In case the force check flag is passed, allow not running it from terminal (e.g. with a debugger).
=> feat: Use `gh` CLI to get GitHub token if available

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/trace/call.go, pkg/trace/call_test.go
* Separate latency metrics into HTTP, gRPC, and Outbound.
**JIRA ID**: [DT-479]
* Bootstrap will be updated after this is merged.
[DT-479]: https://outreach-io.atlassian.net/browse/DT-479
=> feat: Separate Latency Metrics [DT-479]

pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, pkg/trace/call.go, pkg/trace/call_test.go
**JIRA ID**: [DT-479]
[DT-479]: https://outreach-io.atlassian.net/browse/DT-479
=> feat: Readd statuscategory and statuscode [DT-479]

go.mod, pkg/box/box.go, pkg/box/fetch.go
**What this PR does / why we need it**: This PR adds the box configuration library from the devenv into `gobox`. 
**JIRA ID**: [DTSS-493]
[DTSS-493]: https://outreach-io.atlassian.net/browse/DTSS-493
=> feat: add box library

pkg/trace/call.go
=> fix: remove unnecessary return

pkg/trace/call.go, pkg/trace/call_test.go
**What this PR does / why we need it**:  
Cherry-picking commit [c5a08c3e26](https://github.com/getoutreach/go-outreach/commit/c5a08c3e26e935ea50811cd0d61544a6a3d652c6) from the deprecated `go-outreach` package
Logs should be on different levels depending on the statuscategory.
**JIRA ID**:[OREX-420]
[OREX-420]: https://outreach-io.atlassian.net/browse/OREX-420
=> fix: switch log level depending on the error status category [OREX-420]

go.mod, go.sum, pkg/async/async.go, pkg/async/async_test.go, pkg/async/pool/README.md, pkg/async/pool/benchmark_test.go, pkg/async/pool/example_test.go, pkg/async/pool/pool.go, pkg/async/pool/pool_test.go, pkg/async/pool/scheduler.go, pkg/async/pool/timeout.go, pkg/async/pool/timeout_test.go, pkg/async/pool/utils_test.go, pkg/async/pool/wait.go, pkg/async/pool/wait_test.go
* adds async package and child package so we can archive async repository.
=> feat: add async

pkg/metrics/metrics.go, pkg/trace/call.go
* https://outreach-hq.slack.com/archives/CN9MU7GLW/p1628699251299900
=> feat: internal outbound metrics

pkg/trace/force_sampler.go, pkg/trace/force_sampler_test.go, pkg/trace/trace.go
* Allow traces to force their sample rates.
**JIRA ID**: [DTSS-721]
[DTSS-721]: https://outreach-io.atlassian.net/browse/DTSS-721
=> feat: Force Sample Rate for Tracing [DTSS-721]

pkg/box/box.go
**What this PR does / why we need it**: see https://github.com/getoutreach/devenv/pull/70 
**JIRA ID**: [DTSS-0]
=> feat(box): add PostDeployApps

pkg/box/box.go
**What this PR does / why we need it**: As the title says, this does. This is needed for passing the loft URL to all devboxes. 
**JIRA ID**: [DTSS-775]
[DTSS-775]: https://outreach-io.atlassian.net/browse/DTSS-775
=> feat(box): add devenv runtime configuration

go.mod, go.sum, pkg/cli/bootstrap.go, pkg/cli/doc.go
This PR pulls most of the CLI-specific code we have out of bootstrap and instead, putting it inside of gobox. This makes the code much easier to maintain / test and is less duplicated.
Example PR on the devenv: https://github.com/getoutreach/devenv/pull/130
**JIRA ID**: [DTSS-0]
=> feat: abstract out majority of bootstrap CLI code

pkg/cli/bootstrap.go
=> fix: apply overrides in cli

pkg/k8s/resources/resource_status.go
formatted line and its arg were printed as plain text
**JIRA ID**: [QSS-00]
=> fix(log): log line fix

pkg/k8s/controllers/reconciler.go, pkg/k8s/controllers/reconciler_test.go
Delegate Not Found errors to the handler via the new Deleted callback, and add unit test
**JIRA ID**: [QSS-822]
[QSS-822]: https://outreach-io.atlassian.net/browse/QSS-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(reconciler): handle CR Not Found case

pkg/cli/bootstrap.go
Fixes hard to debug issues in CLIs. Still figuring out the true CLI issue.
=> fix(cli): dont panic if no fallback reader is set

internal/call/call.go, internal/call/call_option.go, internal/call/option.go, pkg/trace/call.go, pkg/trace/call_option.go, pkg/trace/call_option_test.go, pkg/trace/call_test.go
We'd like to be able to set scheduled time to have a correct waiting and total time in logs.
=> feat(trace): add scheduled time setter

pkg/region/region.go
* https://outreach-hq.slack.com/archives/CN9MU7GLW/p1646940109106919
[XX-XX]
=> fix: average region duration

pkg/cli/bootstrap.go, pkg/cli/bootstrap_test.go, pkg/telefork/client.go, pkg/telefork/client_test.go, pkg/telefork/telefork.go, pkg/trace/honeycomb.go, pkg/trace/tracetest/tracetest.go
Adding CLI telemetry for bootstrap CLIs. It goes through telefork as that's completely public with no real secrets, so it can go OSS.
Also
[DTSS-1629]
[DTSS-1629]: https://outreach-io.atlassian.net/browse/DTSS-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Added basic Telefok client usable as trace presend hook

pkg/updater/misc.go
support major version import paths
=> fix: support major version import paths

pkg/updater/cli.go
fix: enable `skip-update` to work right
Previously the string was the wrong name so it never skipped.
[DTSS-1841]
[DTSS-1841]: https://outreach-io.atlassian.net/browse/DTSS-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: constant updating

pkg/box/ci.go
**What this PR does**: Title says it does... 🦀
=> fix: add yaml struct tags

pkg/app/info.go
* there was a data race around app.Info
[XX-XX]
=> fix: app info data race

pkg/trace/propagation.go, pkg/trace/roundtripper_test.go, pkg/trace/trace.go, pkg/trace/tracetest/tracetest.go
Handles tests that run in CI without configuring a tracer. For example:
https://app.circleci.com/pipelines/github/getoutreach/settings/1578/workflows/57101a11-0e3d-4783-814a-0d27d9b5dced/jobs/7586
[DTSS-2066]
[DTSS-2066]: https://outreach-io.atlassian.net/browse/DTSS-2066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(trace): handle propagation without tracer

pkg/trace/trace.go
Adds a panic when we can't find a tracing library to use.
[DTSS-2068]
[DTSS-2068]: https://outreach-io.atlassian.net/browse/DTSS-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(trace): add error for manual library upgrade

pkg/async/async.go, pkg/cli/bootstrap.go, pkg/trace/call_test.go, pkg/trace/roundtripper.go, pkg/trace/trace.go, pkg/trace/trace_test.go, pkg/trace/tracer.go
Deprecates functions that are no longer needed with the move to OpenTelemetry.
[XX-XX]
=> feat(trace): deprecate functions

pkg/async/pool/pool.go, pkg/async/pool/pool_test.go
[DT-2317]
[DT-2317]: https://outreach-io.atlassian.net/browse/DT-2317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ensure pool mutex unlock

pkg/async/pool/pool.go
[DT-2317]
[DT-2317]: https://outreach-io.atlassian.net/browse/DT-2317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: close worker on pool close

pkg/async/pool/pool.go, pkg/async/pool/pool_test.go, pkg/async/pool/timeout_test.go
[DT-2317]
[DT-2317]: https://outreach-io.atlassian.net/browse/DT-2317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: better pool tests

pkg/async/pool/pool.go, pkg/async/pool/pool_test.go
=> fix: remove multiple closed listeners

pkg/async/pool/pool.go
[DT-2254]
[DT-2254]: https://outreach-io.atlassian.net/browse/DT-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: close pool based on channel

pkg/async/pool/pool.go, pkg/async/pool/pool_test.go
[DT-2254]
[DT-2254]: https://outreach-io.atlassian.net/browse/DT-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: only check ctx err once

internal/call/call.go
I would like to be able to run tests with race detector on. 
[XX-XX]
=> fix: adding mutex to remove data race

pkg/trace/config.go, pkg/trace/otel.go
Allows configuring additional endpoints and keys so that we can support multiple trace backends at once.
[DT-2637]
[DT-2637]: https://outreach-io.atlassian.net/browse/DT-2637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: support additional endpoint trace config

pkg/trace/propagation.go
[DT-2647]
[DT-2647]: https://outreach-io.atlassian.net/browse/DT-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: skip propagation if not trace found

pkg/cli/updater/options.go, pkg/cli/updater/updater.go, pkg/cli/updater/updater_test.go
Poorly named variable resulted in bad code :'(
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(updater): executableName -> executablePath

pkg/async/async_test.go
Shorten long sleeps.
Fix flaky sleep test.
Strip out tracing.
=> chore: More async test cleanup.

pkg/app/info.go, pkg/app/info_test.go
Get region from MY_REGION to support NGB. 
PS. NGB cluster naming convention does not have <region>
https://outreach-io.atlassian.net/browse/DT-2373
=> fix: read region from MY_REGION

pkg/trace/otel.go, pkg/trace/trace_test.go, pkg/trace/tracetest/tracetest.go
This ensures that we always log the dev email and app info for traces.
[DT-2704]
[DT-2704]: https://outreach-io.atlassian.net/browse/DT-2704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(trace): include dev email

pkg/box/box.go, pkg/box/cd.go
expose cd for devbase to be able to get maestro url via box instead of hardcoding 
https://outreach-io.atlassian.net/browse/DT-2953
=> fix: add cd to box

tools/logger/logger.go
Getting the following error 
```
2022/10/20 13:23:47 Unexpected package creation during export data loading
internal/codegen/protomsg/generate.go:7: running "../../../scripts/shell-wrapper.sh": exit status 1
``` 
without the current changes, this is likely due to changes in go 1.19.
[QSS-1432]
[QSS-1432]: https://outreach-io.atlassian.net/browse/QSS-1432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Fixes errors on marshaller generation

pkg/async/async.go
* runbackground is dangerous. you should always be aware of and control your context.
[STAR-759]
[STAR-759]: https://outreach-io.atlassian.net/browse/STAR-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: deprecate runbackground

pkg/trace/config.go, pkg/trace/otel.go
=> fix(tracing): Correct YAML value for otel collector tracing

pkg/trace/otel.go
We're not sending any traffic outside the cluster to the otel collector, and we don't have TLS termination confgured for this receiver. 
[XX-XX]
=> fix(otel-tracing): use insecure

pkg/box/box.go
=> feat(imageResolver): add config options for image resolver

pkg/trace/config.go, pkg/trace/logfile.go
fix issue where clients are broken sometimes ([thread](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1679596508166189))
[XX-XX]
=> fix: trace logFile

pkg/callerinfo/callerinfo.go
=> fix(DT-3605): Pulling in app.Info().Version for modulever

pkg/callerinfo/callerinfo.go, pkg/callerinfo/callerinfo_test.go, pkg/log/log.go
=> feat: Skipping specific packages for module/modulever log augmenting

.circleci/config.yml, .github/dependabot.yml, .tool-versions, .vscode/private.env, opslevel.yml, scripts/devbase.sh, service.yaml, stencil.lock
=> chore: Re-stencil to remove tier 0

pkg/cli/github/auth.go
This PR adds support for the new Github CLI keyring auth by reading the value out of `gh auth token` command instead of reading it from the file. Originally, this command did not exist, so we had to read it out of the storage file.
[DT-3656]
[DT-3656]: https://outreach-io.atlassian.net/browse/DT-3656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(cli/github): support gh keyring auth format (DT-3656)

.vscode/settings.json, internal/call/call.go, internal/call/option.go, pkg/metrics/metrics.go, pkg/trace/call.go, pkg/trace/call_option.go, pkg/trace/call_option_test.go, pkg/trace/call_test.go, pkg/trace/propagation_test.go, pkg/trace/roundtripper_test.go, pkg/trace/trace_test.go
This PR adds back the functionality added in #300. This part of the code was never broken, so nothing needs to be modified.
[DT-3758]
[DT-3758]: https://outreach-io.atlassian.net/browse/DT-3758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: support disabling logging for trace call methods

pkg/trace/call.go
This code is used already in rms. https://github.com/getoutreach/rms/blob/4e0ec20fd5e46d71a9fa861cce71eebf67bc5494/pkg/protoapi/app/dialect/router/hotswap_resolver.go#L74
Need to get this in so that I can update the marathon pkg to the latest to fix a bulk operation change
=> feat: ability to override traced call Kind

.circleci/config.yml, .github/dependabot.yml, .github/pull_request_template.md, .gitignore, .tool-versions, .vscode/launch.json, .vscode/settings.json, scripts/golangci.yml, stencil.lock
Runs `stencil` to upgrade all the things.
=> feat(stencil): run stencil

pkg/box/box.go
- add default aws account id
https://outreach-io.atlassian.net/browse/DT-4154
=> feat: add default AWS account ID

.circleci/config.yml, cortex.yaml, go.work.sum, service.yaml, stencil.lock
E2E tests don't make sense in this repo.
=> ci: skip E2E tests

pkg/olog/README.md
=> docs(olog): add SetOutput function in README

service.yaml
=> chore: slack notifications channel

pkg/async/retryable_once.go, pkg/async/retryable_once_retry_test.go, pkg/async/retryable_once_test.go
=> fix: add RetryableOnce

.vscode/settings.json, pkg/events/events.go, pkg/events/events_test.go, pkg/events/marshalers.go
- feat: request route to be able to describe HTTP path without extrapolated path variables. This will be used in common service heath dashboard. 
- feat: apiv2 client will be updated to leverage this feature 
[XX-XX]
=> feat(events): add route to context

pkg/log/log.go, pkg/trace/call_option_test.go, pkg/trace/otel.go
[FND-824]
[FND-824]: https://outreach-io.atlassian.net/browse/FND-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(log): emit trace ID in log context

pkg/cli/updater/updater_test.go
Forgot to add this in #663.
[DT-4756]
[DT-4756]: https://outreach-io.atlassian.net/browse/DT-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(cli/updater): add tests for skipPaths functionality
