getoutreach/gobox

- pkg/trace/config.go
- pkg/trace/honeycomb.go
[DT-466](https://outreach-io.atlassian.net/browse/DT-466)
Updates the `trace.yaml` config file to support a new section,
`GlobalTags`.  The idea here is that `GlobalTags` will allow us to
specify in configs certain tags we would like to add to all traces.  The
`MarshalLog` implementation for the `GlobalTags` config struct will
handle converions to standardized tag names.
We start with just one attribute: `DevEmail`/`dev.email`.  This will be
injected into pods via bootstrap so that apps running in the local dev
environment will be tagged with the developer's email, making the
Honeycomb `dev` dataset much easier to navigate.
This is a forward-port of
https://github.com/getoutreach/go-outreach/pull/165.
> feat: DT-466 Support `dev.email` trace tag

- pkg/orerr/orerr.go
- pkg/orerr/orerr_test.go
This adds a new error type that embeds metadata, which must be of type `map[string]string` in order to be used with the [errdetails.ErrorInfo](https://pkg.go.dev/google.golang.org/genproto@v0.0.0-20210708141623-e76da96a951f/googleapis/rpc/errdetails#ErrorInfo) type.
This is meant to support https://github.com/getoutreach/services/pull/134
> Add error metadata for use with grpc 

- pkg/tester/tester.go
- pkg/tester/tester_test.go
**What this PR does / why we need it**:   Adds a tester package compatible with testing.TB
**JIRA ID**: [DTSS-0]
This PR just migrates synthetics/pkg/tester over here as it is a rather small & basic package.    The synthetics repo can now be archived once this lands.
I updated the document comments a bit to be more accurate and renamed LogResultsResults which was incorrectly stuttering + added the tests and also migrated the logger to gobox rather than go-outreach.
> feat(tester): add tester package

- pkg/box/box.go
**What this PR does / why we need it**: As the tile says, it does. This allows granular control over which runtimes are enabled for a devenv. This is useful because they are all ran to detect which is running, so if someone didn't have one disabled it could potentially be ran/downloaded for no reason.
**JIRA ID**: [DTSS-775]
[DTSS-775]: https://outreach-io.atlassian.net/browse/DTSS-775
> feat(box): allow enabling/disabling runtimes for the devenv

- pkg/box/box.go
- pkg/box/fetch.go
- pkg/box/options.go
**What this PR does / why we need it**: This PR adds support for min spec version checks and varidic options for `EnsureBox` 
**JIRA ID**: [DTSS-775]
**Notes for your reviewer**: Big thanks to @malept for discovering the bug that required this.
Related PR: https://github.com/getoutreach/box/pull/4
[DTSS-775]: https://outreach-io.atlassian.net/browse/DTSS-775
> feat(box): support min version checks, expose vardiac options

- pkg/updater/github.go
- pkg/updater/github_test.go
Updater ignored SIGINT before.
**JIRA ID**: [DTSS-557]
After this, the download is cancelled, but extraction will still finish if it started. To prevent that we'd have to wrap the reader in something context aware.
[DTSS-557]: https://outreach-io.atlassian.net/browse/DTSS-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Stop update on context cancellation

- pkg/box/box.go
- pkg/box/development_registries.go
- pkg/box/loft.go
- pkg/region/cache.go
- pkg/region/cloud.go
This PR adds support to `box` for expressing development docker image registries as well as for listing available clusters for loft. This will be used by the devenv for both `tilt` integration as well as with `loft` for picking and choosing which cluster to use for backing a cloud devenv. This is contingent on me getting direct cluster endpoints to also work, but that's digressing.
> feat(box): add new fields for multi-cluster/docker image registry support

- pkg/updater/github.go
The URL you can see on release pages on GitHub redirects to an already authenticated URL (has auth as query params).
This endpoint doesn't allow double auth, and the github client's http client automatically adds Bearer auth header.
Using default http client, we avoid this issue.
You can see the issue being fixed here on  bootstrapbot check.
> fix: Use not-authenticated http client for downloading updates

- go.mod
- go.sum
- pkg/log/adapters/logr.go
- pkg/log/adapters/logr_test.go
This PR adds an adapter for `gobox/pkg/log` that implements the `go-logr/logr.Sink` interface.
> feat(log): add logr adapter

- internal/call/call.go
- internal/call/call_test.go
- internal/logf/logf.go
- pkg/log/log.go
- pkg/log/many.go
- pkg/trace/call.go
- pkg/trace/honeycomb.go
This refactors the trace package which has gotten really unwieldy.
There is no functional change.  Just pulling out some functionality into internal packages. 
I pulled out the recursive marshaling functionality into logf (as well as log.F and log.Many) allowing us to share this between trace and log.
I pulled out the core call tracking functionality into `call`.  
I had more changes but the PR was getting larger, so I decided to shave this off by itself first.
> fix: Refactor pkg/trace and pkg/log a bit by pulling out some helpers into internal/

- pkg/async/async.go
- pkg/async/async_test.go
Adds async functions for running a group of tasks and for closing out tasks.
[QSS-836]
[QSS-836]: https://outreach-io.atlassian.net/browse/QSS-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Adding in closer() and rungroups to async

- pkg/box/box.go
- pkg/box/fetch.go
**What this PR does**: Somehow `*yaml.Node` fails to unmarshal (silently) but `yaml.Node` doesn't. Noice. Cool. Dope.
> fix: properly unmarshal box config

- pkg/box/box.go
- pkg/box/fetch.go
**What this PR does**: We've had this `addressCI` in our box config for ever, but never exposed it. Now we do. 🎉
> fix: support CI address for vault

- pkg/updater/cli.go
Updates the command referenced when saying the `--enable-prereleases` flag is deprecated from `updater set-channel prereleases` (which does not work) to `updater set-channel rc`
[DT-2310]
[DT-2310]: https://outreach-io.atlassian.net/browse/DT-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update command referenced in enable-prereleases deprecation message

- pkg/log/log.go
We have been seeing random gobox/pkg/log [failures](https://app.circleci.com/pipelines/github/getoutreach/litmus/860/workflows/4fd62025-64b4-47b1-b848-5f854791409f/jobs/3523) in the CI. The root cause is `SetOutput()` and `Write()` are called concurrently trying to set/read the `stdOut` object at the same time. This change puts a lock around the `stdOut` object to guard it so that it is thread safe.
[XX-XX]
> feat: add lock to guard stdOut

- pkg/cli/bootstrap.go
- pkg/cli/bootstrap_test.go
- pkg/cli/updater/urfave_cli.go
Eject into shell completion mode immediately, without completing logging and tracing setup. This dramatically increases the responsiveness of shell completion, and also avoids injecting updater messages into the completion suggestions.
Add a special flag for fish completion, since there is none built-in for urfave.
See [the urfave manual](https://cli.urfave.org/v2/#bash-completion) for details on bash / zsh / powershell completion. The TL;DR is urfave supplies [helper scripts](https://github.com/urfave/cli/tree/8b23e7b1e99f37934e029ef6c8d31efc7e744ff1/autocomplete) that you can source to make completion work.
Fish support [exists](https://github.com/urfave/cli/blob/8b23e7b1e99f37934e029ef6c8d31efc7e744ff1/fish.go), but is undocumented in the manual and kind of wonky, since you must invoke …
> feat(cli): Better shell completion support.

- pkg/trace/otel.go
- pkg/trace/propagation.go
- pkg/trace/span_start_options.go
- pkg/trace/trace.go
- pkg/trace/trace_test.go
- pkg/trace/tracer.go
- pkg/trace/tracetest/tracetest.go
Clerk needs to link producer spans with consumer ones cross VM boundaries. In order to do so, we need gobox's trace support to start a span with a link. Clerk already propagates traceHeaders as part of the event, so this PR is to take the same headers (map[string][]string - same as existing To/FromHeaders methods) and generate a link out of them + attach the link as a new StartSpanOption. StartSpanOption abstracts out otel implementation ...
[CDT-102]
[CDT-102]: https://outreach-io.atlassian.net/browse/CDT-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(trace): SpanStartOption and WithLinks

- go.mod
- go.sum
- pkg/cli/updater/misc.go
- pkg/cli/updater/release/github.go
- pkg/cli/updater/release/release.go
- pkg/cli/updater/resolver/resolver.go
- pkg/cli/updater/resolver/resolver_test.go
- pkg/cli/updater/resolver/sort.go
- pkg/cli/updater/updater.go
- pkg/cli/updater/updater_test.go
- pkg/cli/updater/urfave_cli.go
This PR adds [constraint support](https://pkg.go.dev/github.com/Masterminds/semver/v3#hdr-Checking_Version_Constraints_and_Comparing_Versions) to the version resolver used by the updater. This allows other consumers to add semver constraints to change the versions selected by the resolver.
The general behaviour of this package is well documented in the tests written, but also in the package comment for `Resolve`, copied here for posterity:
```go
// Resolve returns the latest version that satisfies the criteria
//
// Note: token is _optional_, if you do not wish to authenticate with your VCS
// provider you can pass an empty string.
//
// Criteria:
//
// Constraints are supported as per the underlying semver library here:
// https://pkg.go.dev/github.com/Masterminds/semver/v3#hdr-Checking_V …
```
> feat(updater/resolver): support constraints (DT-2120)

- pkg/async/pool/pool_test.go
- pkg/async/pool/timeout_test.go
- pkg/async/pool/wait.go
Fix a test whose slow task would sometimes complete too early, breaking a timeout test.
Fix a test that would sometimes cancel too early, causing too few tasks to finish. Also load shared memory atomically, just for completeness.
Clean up some grammar in godoc.
These tests are super-flaky, and hopefully this fixes them.
> chore: Unit test fixes.

- pkg/cli/updater/resolver/resolver.go
- pkg/cli/updater/resolver/resolver_test.go
- pkg/cli/updater/resolver/sort.go
- pkg/cli/updater/updater.go
- pkg/cli/updater/updater_test.go
- pkg/cli/updater/urfave_cli.go
This PR changes the updater to properly compare mutable versions, and providers a function to create a, lossy, mutable version from the version string.
This, combined with the new `LessThan` and `Equal` functions allows us to potentially use this logic other places (as it makes sense)
I also added this information to the `updater status` command so it'll be easier to track down why this happened in the future.
[DT-2815]
[DT-2815]: https://outreach-io.atlassian.net/browse/DT-2815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(updater): properly compare mutable versions

- pkg/app/info.go
- pkg/cli/updater/updater.go
This PR makes the updater disable itself when an invalid version is provided. I also updated `app` to source version information, if not linked in, from the go module. This lets `go run` and (theoretically, I can't test w/o a release) work on `go install` (and `go run <module>@<revision>`). Unclear if this will support gobin, but it'll at least make `--skip-update` a valid argument.
Example on a locally compiled version of `smartstore` w/ `replace` for this version:
```bash
$ go run ./cmd/smartstore updater status
Version: (devel)
Channel:  ()
Updater Status: disabled (failed to parse current version as semver: Invalid Semantic Version)
Last Update Check: Mon, 26 Sep 2022 18:11:52 UTC
```
[DT-2907]
[DT-2907]: https://outreach-io.atlassian.net/browse/DT-2907?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> feat: handle invalid semver, support go run/install/gobin

- pkg/env/e2eenv.go
- pkg/env/readers.go
- pkg/env/testenv.go
* env.FakeTestConfig was causing a data race in parallelized tests
because it wasn't protected via a mutex (or anything to prevent a
data race).
[XX-XX]
> fix: env test override data race

- pkg/queue/example_queue_test.go
- pkg/queue/queue.go
- pkg/queue/queue_test.go
It does not make sense for a queue capacity to be negative. This PR changes the queue capacity type to be `uint` so that creating a queue is simpler without handling the return error. 
[XX-XX]
> feat: change queue capacity type to uint

- pkg/cli/updater/resolver/resolver.go
- pkg/cli/updater/resolver/resolver_test.go
- pkg/sshhelper/sshhelper.go
This PR contains fixes to a few CLI-oriented packages. Primarily it contains a fix for the `resolver` package.
This fix ensures that when consider a branches (with `AllowBranches`) that we do not insert a mutable version for that branch on to the channel. The problem with doing so is that a mutable version is always ranked higher than tags, this is problematic for branches that _only_ release and support tags on the branch (e.g. `rc` vs `unstable`).
We now filter out the mutable insertion after converting references into their channel/version pair, if we have a tag then we remove the latest version (if it's mutable). It will always be the latest version because of the sorting logic (which broke this library) in the previous PR.
This is a small fix to the logic to support read-only …
> fix(cli): small fixes to logic in CLI package(s)

- pkg/cli/bootstrap.go
- pkg/cli/bootstrap_test.go
when run in production, the trace.yaml override breaks tracing for
containers that don't use ldflags to set the honeycomb api key.
This simply tries to load trace.yaml before falling back to the CLI's
overrides
[QSS-1588]
[QSS-1588]: https://outreach-io.atlassian.net/browse/QSS-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(cli): try load trace.yaml before overriding

- pkg/tester/tester.go
Allows for Run to receive mismatched types between t and f. We were getting panics in sequencetest when running with t and f being of different types.
[XX-XX]
Sorry no Jira ID, just trying to fix up sequencetest's usage of this pkg.
> fix: support Run receiving t *testing.T and f of type tester.T

- pkg/callerinfo/callerinfo.go
- pkg/callerinfo/callerinfo_test.go
- pkg/log/adapters/adapters_test.go
- pkg/log/caller_test.go
- pkg/log/fatal_test.go
- pkg/log/log.go
- pkg/log/log_test.go
- pkg/log/with_test.go
Walking stack with caching stack frame lookups to find out who is calling the logger and adding it to all formatted logs.  Intent is to be able to filter out what application is the actual source of logs for filtering/cost attribution.
> feat: Adding "module" field to logs with module of actual logger

- pkg/shuffler/doc.go
- pkg/shuffler/suite.go
- pkg/shuffler/suite_test.go
Deprecates the `shuffler` package in favor of native go testing (shuffling is supported OOTB since 1.17 and we've enabled it). Also removes `!or_e2e` constraint due to this causing compilation issues in some packages.
[XX-XX]
[**Internal Slack Thread**](https://outreach-hq.slack.com/archives/C03RV4VGAE7/p1677791110515529)
> fix(shuffler): deprecate shuffler package, allow build when or_e2e is set

- pkg/orerr/bad_request.go
- pkg/orerr/orerr_test.go
This PR are aiming to add a generic bad request validation that complies with localization requirements and propagates from the grpc server to its client. 
https://github.com/getoutreach/gobox/pull/275
https://github.com/getoutreach/services/pull/395
https://outreach-io.atlassian.net/browse/ES-3183
https://github.com/getoutreach/services/pull/395/files
> feat: bad request error

- pkg/trace/otel.go
- pkg/trace/otel_test.go
passing events.NewErrorInfo(nil), a totally valid use case, was sufficient to cause a panic. This adds a smatterring of nil checks in the type switch to ensure we don't hit that.
[XX-XX]
> fix(trace): usage revealed a panic

- pkg/differs/floats.go
This PR adds a `differs.AnyFloat64()` function which allows any `float64` value when doing a diff using `cmp.Diff()`. This is an alternative to `FloatRange` where you do not care what the value is (e.g., duration) but want the value to be of a specific type.
> feat(differs): add AnyFloat64

- .vscode/settings.json
- internal/call/call.go
- internal/call/option.go
- pkg/metrics/metrics.go
- pkg/trace/call.go
- pkg/trace/call_option.go
- pkg/trace/call_option_test.go
- pkg/trace/call_test.go
- pkg/trace/propagation_test.go
- pkg/trace/roundtripper_test.go
- pkg/trace/trace_test.go
This PR adds a `CallOptions` type that can be used for specific options for tracing calls. Ideally, this would be limited to artifacts of traces (e.g., logs). The first, and only, option implemented is `DisableInfoLogging`. This defaults to `false`. When set to `true`, info logs are not generated when a call ends.'
I also cleaned up some tests to no longer be attached to the test suite struct invoked by `shuffler.Run()`. This helps us when we fully remove the shuffler in favor of using standard go testing.
Updated the `gopls` build flags to not include `or_e2e` for invocation of tests through VSCode and compilation. This doesn't really matter except for some packages, ideally we'll remove these tags entirely in the future when we stop using build tags to handle configuration loading logic …
> feat(trace): Support disabling logging for trace call methods

- pkg/callerinfo/callerinfo.go
- pkg/callerinfo/callerinfo_test.go
> fix(DT-3663): Function names can be >2-part names, fixing module name calculator

- .vscode/settings.json
- internal/call/call.go
- internal/call/option.go
- pkg/metrics/metrics.go
- pkg/trace/call.go
- pkg/trace/call_option.go
- pkg/trace/call_option_test.go
- pkg/trace/call_test.go
- pkg/trace/propagation_test.go
- pkg/trace/roundtripper_test.go
- pkg/trace/trace_test.go
Reverts getoutreach/gobox#300
[DT-3752]
**[Slack Context](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1684526326001109)**
[DT-3752]: https://outreach-io.atlassian.net/browse/DT-3752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> revert: support disabling logging for trace call methods (#300)

- pkg/cli/logfile/logfile_unix.go
This PR fixes the stdin logic to properly pass stdin to the created sub-process when running not as a terminal. When running in a terminal, this is properly handled by the `ptyOutputHook` function.
[DT-3742]
[DT-3742]: https://outreach-io.atlassian.net/browse/DT-3742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(delibird): pass stdin to subproccess when not term

- pkg/box/box.go
This is the first part of 3 changes. Following changes are:
- Define Restore steps in devenv-snapshots https://github.com/getoutreach/devenv-snapshots/pull/130
- Support Restore steps in devenv: https://github.com/getoutreach/devenv/pull/677
[QF-909](https://outreach-io.atlassian.net/browse/QF-909)
[QF-909]: https://outreach-io.atlassian.net/browse/QF-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Extend SnapshotTarget with RestoreSteps

- README.md
Updated some leftover links to point to pkg.go.dev, their equivalent today.
Slightly cleaned up some words.
> docs(README): update links and some wording

- pkg/statuscodes/statuscode_string.go
- pkg/statuscodes/statuscodes.go
- pkg/statuscodes/statuscodes_test.go
This happens when a server already cancels a request. This will enable better metrics tracking. There were cases where due to a context being canceled an InternalServerError returned. This would cause alerts to trigger when in fact the only issue was that the context was canceled.
[STAR-1788]
This was an issue that was happening for marathon. By the time the server goes to make the request the context has been canceled. At this point its best to simply return "ClientCanceled"
More discussion came from this slack thread.
https://outreach-hq.slack.com/archives/CN9MU7GLW/p1691689393028399
This PR is simply the first part of what was already discussed.
[STAR-1788]: https://outreach-io.atlassian.net/browse/STAR-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> feat: add capability to have a status code for client canceled.

- pkg/cli/aws/aws.go
This is basically the business logic needed to create a CLI command to generate AWS credentials, either by writing them to the well-known AWS credentials file, or emitting credential provider compliant JSON.
> feat(aws): add authorize func that can optionally emit credential provider JSON

- pkg/box/box.go
- pkg/cli/aws/aws.go
- pkg/cli/aws/aws_test.go
If `role` is empty, omit the IAM role from the respective CLIs and make them set the role interactively.
[DT-3999]
Adds some tests for `refreshCredsViaOktaAWSCLI`.
[DT-3999]: https://outreach-io.atlassian.net/browse/DT-3999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(aws): add interactive role selection; MFA for saml2aws

- pkg/async/pool/ORIGINAL_README.md
- pkg/async/pool/README.md
- pkg/async/pool/pool.go
- pkg/async/pool/scheduler.go
- pkg/async/pool/timeout.go
- pkg/async/pool/wait.go
Deprecates the major methods in `async/pool` in favor of using
`github.com/sourcegraph/conc/pool` instead. The `async/pool` has had
usability issues for a long time now, namely hard to use `Wait()` as
well as almost impossible to get errors out of. The `conc/pool` library
is a much better, more actively maintained libary.
Included is a new `README.md` with instructions on how to migrate all
usecases I could discern from across the `getoutreach` organization.
The main change here is the removal of bufferred pools of work items
that could be dynamically resized as well as rejected if there was no
room. I could only find one repo, `mailroomapi`, that used this
functionality. It is likely that the block until accepted behaviour will
be more acceptable to this service, but also I don't feel …
> feat: Deprecate async/pool in favor of github.com/sourcegraph/conc/pool

- pkg/trace/force_sampler.go
- pkg/trace/logfile.go
- pkg/trace/otel.go
- pkg/trace/propagation.go
- pkg/trace/propagation_test.go
- pkg/trace/tracer.go
[DT-4023](https://outreach-io.atlassian.net/browse/DT-4023)
Updates the implementation of `trace.ForceTracing(ctx)` such that it has
an effect only when its returned `ctx` is used.  The modified `ctx` will
always sample any spans associated with it.  Any requests made with this
`ctx` will send an `X-Force-Trace` header to the receiving service.
However, there will be no impacts outside of this particular `ctx`.
Previously, this method would set an effectively process-global flag and
enable force-trace behaviors process-wide.  This is not what the
function signature suggests it does and probably not what its callers
would expect.
Since we're poking at the `otelForceSampler` code anyway, updates the
decisions returned by `ShouldSample` to include a proper "SampleRate"
attribute.  This will …
> fix: DT-4023 Fix tracing.ForceSample + SampleRate

- internal/call/option.go
- pkg/trace/call.go
- pkg/trace/call_option.go
- pkg/trace/call_option_test.go
- pkg/trace/config.go
- pkg/trace/otel.go
- pkg/trace/trace.go
- pkg/trace/tracetest/tracetest.go
[DT-4029](https://outreach-io.atlassian.net/browse/DT-4029)
Disables the info logs that would previously occur as part of a
`trace.StartCall`'s succesful completion.  Calls that end in errors have
been and will continue to be logged.
Adds a boolean config option to `trace.yaml` so that services can opt
back in to the old behavior.  We don't want services to fear upgrading
to this version of gobox; this flag will let them upgrade without
experiencing an unpleasant behavior change.
Adds a new call option to explicitly enable info logs for particular
instances of `trace.StartCall`.  We hope that folks that rely on these
logs will rely on this more targeted approach to meet their needs,
rather than using the service-wide `trace.yaml` opt-out.
If you would like to keep your service on the more …
> feat: DT-4029: Disable call info logging default

- pkg/cli/updater/updater.go
Updater package defines `Disabled bool` that should be usable as a global kill switch of updater services. Unfortunately it is useless:
- the suggested usage via ldflags does not work. It fails `github.com/getoutreach/gobox/pkg/cli/updater.Disabled: cannot set with -X: not a var of type string (type:bool)` and [documentation](https://pkg.go.dev/cmd/link) is clear - it must be string if we want to use it this way.
- alternatively if you try `updater.Disabled = true` it does not really disable the initialization which likely fails and logs a warning.
So this PR fixes the behavior. Turns it into string and stops `defaultOptions()` successfully.
> fix: make updater.Disabled usable

- pkg/box/box.go
- pkg/cli/aws/aws.go
Remove the code to support use of `saml2aws` for AWS credentials as Outreach no longer uses it, while retaining the refactor to allow future non-`okta-aws-cli` implementations if necessary.
This doesn't completely remove all traces of `saml2aws` as we still use their AWS credentials reader API to see if the credentials are expired.
> feat(aws): remove saml2aws support

- pkg/pointer/pointer.go
- pkg/pointer/pointer_test.go
This PR aims to add a pointer package to be used across our services and librairies. 
I had to do pointer conversion in API-Proxy [here](https://github.com/getoutreach/apiproxy/blob/f3707830d6d25f94057182027037c709d7a14c4d/internal/apiv2/openapi.go#L33) and saw `ptr.SomeType()` in several places (not using generic). 
As we are using gql federation in our services we will surely need more pointer conversion and I would like to have the possibility to use generics.
- Added tests with different types including some that are not supported by [github.com/aws/smithy-go/blob/main/ptr](https://github.com/aws/smithy-go/blob/main/ptr)
No Jira, just an idea of package that would be nice to have
> feat: Add Pointer Package

- go.mod
- go.sum
- pkg/cli/github/github.go
- pkg/cli/updater/release/github.go
Updates to the latest major version - a bunch of repos use different major versions, so let's try to get these all using the same one.
> fix: upgrade google/go-github to v58

- pkg/box/fetch.go
- pkg/box/options.go
This is needed in order to pass in a private SSH key from a Kubernetes secret into a job that needs the box config.
> feat(box): add option to provide SSH agent

- pkg/trace/otel.go
If the otel collector endpoint is specified we should _not_ initiation a new client for honeycomb.
[DT-4286]
[DT-4286]: https://outreach-io.atlassian.net/browse/DT-4286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: stop dual initiation of trace clients

- pkg/maps/maps.go
- pkg/maps/maps_test.go
I need to merge maps time to time and I lack quite often of a function to do that. For now I would just have duplicated piece of code
```golang
for k, v := a {
b[k] = v
}
```
Tbh it is okay but 
```golang
a = maps.Merge(a, b, true)
```
is easier to read.
[XX-XX]
> feat: New Maps Package

- go.mod
- go.sum
- go.work.sum
- pkg/box/fetch.go
- pkg/cli/github/github.go
- pkg/cli/updater/release/github.go
If the box config comes from GitHub, use the GitHub API to download it. Otherwise fall back to the `git+ssh` method.
[DT-4362]
[DT-4362]: https://outreach-io.atlassian.net/browse/DT-4362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(box): use GitHub API to download config when appropriate

- go.mod
- go.work.sum
- pkg/olog/logrus.go
- pkg/olog/logrus_test.go
Add a charm-style formatter for logrus to have consistent logging formats.
`log/slog` has been widely accepted by the community as the new standard for logging in Go. This olog package is our implementation of it which uses the charm logger. However, we are currently using logrus in many places for CLI applications. In order to have consistency in our log formats, I decided to create a custom logrus formatter which matches the text format of the charm logger.
Most of this is copied from the [charm text formatter](https://github.com/charmbracelet/log/blob/82b5630d2e68c2cf4c972a926be90149fe0c60b9/text.go), but it's been slightly tweaked. The `Format` method is what fulfills the logrus interface. It creates the right request shape and byte buffer to call into `textFormatter`. The bytes are …
> feat(olog): add charm-style formatter for logrus

- pkg/statuscodes/statuscode_string.go
- pkg/statuscodes/statuscodes.go
- pkg/statuscodes/statuscodes_test.go
This happens when a user/caller cancels the request before being finished. This will improve our metrics, because such cases are reported as InternalServerError currently. 
[RMS-4688]
[RMS-4688]: https://outreach-io.atlassian.net/browse/RMS-4688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add capability to have a status code for request being cancelled

- pkg/trace/call.go
We are already logging trace IDs in EndCall, but we don't do it in StartCall.
Thus we currently cannot distinguish correctly between the requests.
With this PR the `trace_id` is present correctly:
[XX-XX]
> fix: log trace IDs in StartCall

- pkg/olog/olog.go
Make the SetOutput function thread safe.
[XX-XX]
> fix(olog): add lock to SetOutput

- pkg/trace/propagation.go
- pkg/trace/roundtripper.go
- pkg/trace/tracer.go
API Proxy uses NewHandler tracer and it currently "attaches" to trace contexts defined by external callers which may result in useless massive traces saved in our Honeycomb. [Example](https://ui.honeycomb.io/outreach-a0/datasets/outreach/result/FK9qSb6NoWh/trace/hkZSeQZ1mUu?fields%5B%5D=s_name&fields%5B%5D=s_serviceName&fields%5B%5D=c_http.url&span=53cc10310e79186b)
Instead the service shall attach to "internal" callers such as DSNG Sync and Trigger services but reset parent trace for requests initiated by "external" callers. And for that it is necessary to wire [WithPublicEndpointFn](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp#WithPublicEndpoin …
> feat(trace): propagate WithPublicEndpointFn to otel NewHandler

- pkg/metrics/metrics.go
- pkg/trace/call.go
- pkg/trace/call_test.go
- pkg/trace/resolver.go
Your service can implement custom evaluation function to control emission of trace.StartCall info logs from Go services in real time based on as granular conditions as you wish.
> feat: allow controlling of StartCall info logging from a service runtime

- pkg/cli/aws/aws.go
- pkg/cli/aws/aws_test.go
Adding support to set `--debug` and `--debug-api-calls` may be helpful when debugging strange issues with `okta-aws-cli`.
> feat(aws): add debug flags

- pkg/box/box.go
Will allow Stencil and its modules to use the box value, once it's updated with the version this is released with.
[DT-4745]
[DT-4745]: https://outreach-io.atlassian.net/browse/DT-4745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(box): add support for engdocs.URL

- pkg/events/events.go
After migration from Google to MS we lost links in this repository. This PR fixes the link to the new destination.
> chore: update Google link to MS

- pkg/cli/updater/updater.go
- pkg/cli/updater/urfave_cli.go
- pkg/exec/exec.go
- pkg/exec/exec_test.go
Does what it says on the tin.
Eventually the deprecated misspelled function will be removed.
[DT-4756]
[DT-4756]: https://outreach-io.atlassian.net/browse/DT-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(cli/updater): typo in ResolveExecutable name

- go.work.sum
- pkg/cli/aws/aws.go
- pkg/cli/aws/aws_test.go
* Replaces the deprecated `--session-duration` flag with `--aws-session-duration`.
* Adds an expiry field to the AWS credentials file.
[DT-4767]
[DT-4767]: https://outreach-io.atlassian.net/browse/DT-4767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(aws): replace deprecated flag, add expiry entry

- pkg/cli/cli.go
We detected the issue since a consuming tool (`devenv`) stopped returning `1` on error.
`defer` does nothing with the returned `func()`, dev has to call that further.
[XX-XX]
> fix(cli): regression related to cleanup/exit functions

- go.work.sum
- pkg/trace/otel.go
- pkg/trace/otel_test.go
- pkg/trace/trace.go
- pkg/trace/trace_test.go
- pkg/trace/tracer.go
- pkg/trace/tracetest/tracetest.go
events are the way your supposed to send information about points in time during your span. See https://opentelemetry.io/docs/specs/otel/trace/api/#add-events This PR adds support for them, because I wanted to use them in polaroid to report progress on checking an SLo without creating tiny lil nanosecond duration spans.
trace.Error was supposed to do the proper error reporting, but it did so in a bit of a convoluted way and the testing utility actually hid the necessary component from the developer, so I exposed that utility, wrote a better test, and then updated trace.Error to actually consistently report errors.
[XX-XX]
> feat(trace): fix trace.Error and support sending events directly.
